Repository microsoft/fluentui-apple, pull requests merged in 2021-12, with the labels that each got.

#812 Bumping versions for FluentUI release (0.3.8).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#825 Bumping versions for FluentUI release (0.3.9).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#831 Bumping versions for FluentUI release (0.4.1).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#814 Converting PillButtonBar to vNext
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Pill Button Bar/MSFPillButtonBarTokens.generated.swift
  ios/FluentUI/Pill Button Bar/MSFPillButtonTokens.generated.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
  ios/FluentUI/Pill Button Bar/PillButtonBarTokens.swift
  ios/FluentUI/Pill Button Bar/PillButtonStyle.swift
  ios/FluentUI/Pill Button Bar/PillButtonTokens.swift
  tools/sgen/input/FluentUIStyle.yml
  tools/sgen/output/MSFNotificationTokens.generated.swift
  tools/sgen/output/MSFPillButtonBarTokens.generated.swift
  tools/sgen/output/MSFPillButtonTokens.generated.swift
Labels: vnext-prototype

#834 Convert `ColorValue` from a pure `UInt32` to a wrapper struct
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ThemingDemoController.swift
  ios/FluentUI.Tests/ColorTests.swift
  ios/FluentUI/Core/Theme/DynamicColor.swift
  ios/FluentUI/Core/Theme/Tokens/ColorSet.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Extensions/UIColor+Extensions.swift
Labels: vnext-tokens

#838 [vNext Tokens] Delete `DynamicColor`
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Card Nudge/CardNudge.swift
  ios/FluentUI/Core/Theme/DynamicColor.swift
  ios/FluentUI/Core/Theme/Tokens/ColorSet.swift
Labels: vnext-tokens

#842 [vNext Tokens] Rename ColorSet -> DynamicColor
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ThemingDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Card Nudge/CardNudge.swift
  ios/FluentUI/Card Nudge/CardNudgeTokens.swift
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarTokens.swift
  ios/FluentUI/Core/Colors.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Core/Theme/Tokens/DynamicColor.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Extensions/UIColor+Extensions.swift
Labels: vnext-tokens
