Repository microsoft/fluentui-apple, pull requests merged in 2021-09, with the labels that each got.

#701 Bumping versions for FluentUI release (0.3.2).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#710 Fixing failed validation due to Redundant Optional Initialization
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: vnext-prototype

#702 [List vNext] Add animation to expand/collapse trigger
  ios/FluentUI/Vnext/List/List.swift
Labels: vnext-prototype

#718 Bumping versions for FluentUI release (0.3.3).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#719 [vNext Tokens] Adding `vnext-tokens` branch to CI pipeline.
  .github/workflows/ci.yml
Labels: vnext-tokens

#705 [vNext CCB] Tokenizing Command Bar
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarButtonGroupView.swift
  ios/FluentUI/Command Bar/CommandBarTokens.swift
  ios/FluentUI/Command Bar/MSFCommandBarTokens.generated.swift
  tools/sgen/input/FluentUIStyle.yml
  tools/sgen/output/MSFCommandBarTokens.generated.swift
Labels: vnext-prototype

#725 Bumping versions for FluentUI release (0.3.4).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update
