Repository microsoft/fluentui-apple, pull requests merged in 2022-11, with the labels that each got.

#1335 Exposing attributedString properties in TableViewCell
  ios/FluentUI/Table View/TableViewCell.swift
Labels: New API

#1287 [Fluent 2 iOS] Updating Button to Fluent 2
  ios/FluentUI/Button/Button.swift
Labels: fluent2-colors 🎨

#1340 [Fluent 2 iOS] Avatar presence colors update
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/MSFAvatarPresence.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1342 [Fluent 2 iOS] Adding guard to Button themeDidChange
  ios/FluentUI/Button/Button.swift
Labels: fluent2-colors 🎨

#1345 [Fluent2 colors] Merge `main`
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Table View/TableViewCell.swift
  macos/FluentUI/AvatarView/AvatarView.swift
  macos/FluentUIUnitTest/AvatarViewTests.swift
Labels: fluent2-colors 🎨

#1330 [Fluent 2 iOS] Drawer colors update
  ios/FluentUI/Drawer/DrawerController.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
Labels: fluent2-colors 🎨

#1348 [Fluent 2 iOS] Fix Avatar colors
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/AvatarTokenSet.swift
Labels: fluent2-colors 🎨

#1296 Create functionality to apply multiple shadows on a view
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShadowTokensDemoController.swift
  ios/FluentUI/Card/CardView.swift
  ios/FluentUI/Core/SwiftUI+ViewModifiers.swift
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
Labels: fluent2-colors 🎨

#1353 Shadows for Tooltip, Notification, BottomSheetController and BottomCommandingController
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Tooltip/TooltipView.swift
Labels: fluent2-colors 🎨

#1358 Merge main into fluent2-tokens
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeFieldDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PeoplePickerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/AvatarGroup/AvatarGroup.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
  ios/FluentUI/Core/Theme/Tokens/DynamicColor.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Divider/Divider.swift
  ios/FluentUI/Divider/DividerTokenSet.swift
  ios/FluentUI/Divider/MSFDivider.swift
  ios/FluentUI/Extensions/UIColor+Extensions.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Resources/Localization/en.lproj/Localizable.strings
  ios/FluentUI/Separator/Separator.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/README.md
  macos/FluentUI/AvatarView/AvatarView.swift
  macos/FluentUIUnitTest/AvatarViewTests.swift
Labels: fluent2-tokens

#1359 Merge main into fluent2-colors
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeFieldDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DividerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DividerDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/IndeterminateProgressBarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PeoplePickerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Calendar/CalendarView.swift
  ios/FluentUI/Core/Theme/Tokens/DynamicColor.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerView.swift
  ios/FluentUI/Divider/Divider.swift
  ios/FluentUI/Divider/DividerTokenSet.swift
  ios/FluentUI/Divider/MSFDivider.swift
  ios/FluentUI/Drawer/DrawerPresentationController.swift
  ios/FluentUI/Extensions/UIColor+Extensions.swift
  ios/FluentUI/Navigation/Shy Header/ShyHeaderView.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/People Picker/PeoplePicker.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
  ios/FluentUI/Resources/Localization/en.lproj/Localizable.strings
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Tab Bar/TabBarView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/README.md
Labels: fluent2-colors 🎨

#1354 [fluent2 tokens] Add scrolling and faded edges to the SegmentedControl
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI/SegmentedControl/SegmentPillButton.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
Labels: fluent2-tokens, New API

#1360 Add checks in themeDidChange functions
  ios/FluentUI/Badge Field/BadgeField.swift
  ios/FluentUI/Card/CardView.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Label/Label.swift
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Navigation/SearchBar.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/ResizingHandleView/ResizingHandleView.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
Labels: fluent2-colors 🎨

#1366 Update avatar ring color for outlined and overflow styles
  ios/FluentUI/Avatar/AvatarTokenSet.swift
Labels: fluent2-colors 🎨

#1349 Implement the Unread Dot for TabBar and SideTabBar
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TabBarViewDemoController.swift
  ios/FluentUI/Resources/Localization/en.lproj/Localizable.strings
  ios/FluentUI/Tab Bar/TabBarItem.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
Labels: New API

#1373 Remove TableViewHeaderFooterView divider styles + references
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewHeaderFooterSampleData.swift
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: fluent2-colors 🎨

#1384 [Fluent 2 Tokens] Merge main
  .github/PULL_REQUEST_TEMPLATE.md
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PersonaListViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PillButtonBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TabBarViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Resources/Localization/en.lproj/Localizable.strings
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/Shimmer/ShimmerLinesView.swift
  ios/FluentUI/Shimmer/ShimmerView.swift
  ios/FluentUI/Tab Bar/TabBarItem.swift
  ios/FluentUI/Tab Bar/TabBarItemTokenSet.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  scripts/xcode_select_current_version.sh
Labels: fluent2-tokens

#1399 [Fluent 2 iOS] Merge main
  .github/PULL_REQUEST_TEMPLATE.md
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/ColoredPillBackgroundView.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PersonaListViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PillButtonBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TabBarViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Date Time Pickers/Date Picker/DatePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/DateTimePickerController.swift
  ios/FluentUI/Drawer/DrawerController.swift
  ios/FluentUI/Resources/Localization/en.lproj/Localizable.strings
  ios/FluentUI/SegmentedControl/SegmentPillButton.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/SegmentedControl/SegmentedControlTokenSet.swift
  ios/FluentUI/Shimmer/ShimmerLinesView.swift
  ios/FluentUI/Shimmer/ShimmerView.swift
  ios/FluentUI/Tab Bar/TabBarItem.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  scripts/xcode_select_current_version.sh
Labels: fluent2-colors 🎨

#1406 [Fluent 2 iOS] Update Alias Color Tokens
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AliasColorTokensDemoController.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Navigation/SearchBar.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/Pill Button Bar/PillButtonStyle.swift
Labels: fluent2-colors 🎨

#1410 [Fluent 2 iOS] Re-do Segmented Control Colors
  ios/FluentUI/SegmentedControl/SegmentedControlTokenSet.swift
Labels: fluent2-colors 🎨
