Repository microsoft/fluentui-apple, pull requests merged in 2022-10, with the labels that each got.

#1279 [main -> fluent2-tokens] Update fluent2-tokens
  .ado/CGManifest.json
  .ado/fluentui-apple-cgcomponentdetection.yml
  .github/actions/uploadSizeArtifact/action.yml
  .github/workflows/sizeComparison.yml
  MicrosoftFluentUI.podspec
  README.md
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarGroupDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI/AvatarGroup/AvatarGroup.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarButtonGroupView.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
  ios/FluentUI/Navigation/NavigationController.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
  scripts/compare_demo_sizes.sh
Labels: fluent2-tokens

#1276 [fluent2-tokens] Fixed SegmentedControl's masked content
  ios/FluentUI/SegmentedControl/SegmentPillButton.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
Labels: fluent2-tokens

#1281 [Fluent 2 iOS] Adding new stroke thickness definitions, updating usage
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/Vnext/Button/ButtonTokenSet.swift
Labels: fluent2-tokens

#1280 [Fluent 2 iOS] 'Other cells' colors update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Other Cells/BooleanCell.swift
  ios/FluentUI/Other Cells/CenteredLabelCell.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: fluent2-colors 🎨

#1283 [Fluent 2 iOS] Updating Stroke Width Definitions
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
Labels: fluent2-colors 🎨

#1285 [Fluent 2 iOS] Updating stroke width for controls to align with new design
  ios/FluentUI/Button/Button.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/Separator/Separator.swift
Labels: fluent2-colors 🎨

#1286 Merge tokenized Shimmer into main
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Shimmer/ShimmerLinesView.swift
  ios/FluentUI/Shimmer/ShimmerTokenSet.swift
  ios/FluentUI/Shimmer/ShimmerView.swift
Labels: API break

#1277 [Fluent 2 iOS] Separator color update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI/Calendar/CalendarView.swift
  ios/FluentUI/Drawer/DrawerPresentationController.swift
  ios/FluentUI/Navigation/Shy Header/ShyHeaderView.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Separator/Separator.swift
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Tab Bar/TabBarView.swift
  ios/FluentUI/Table View/TableViewCell.swift
Labels: fluent2-colors 🎨

#1295 Make PillButtonBarItem title mutable and set its font earlier
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PillButtonDemoController.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
Labels: New API

#1298 [Fluent 2 iOS] CardNudge Update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AliasColorTokensDemoController.swift
  ios/FluentUI/Card Nudge/CardNudge.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1271 [Fluent 2 iOS] Fix HUD color contrast issues
  ios/FluentUI/HUD/HeadsUpDisplayTokenSet.swift
Labels: fluent2-colors 🎨

#1293 Update iPad CommandBar group spacing, propagate accessibilityValue from CommandBarItem to CommandBarButton, and add accentImage to CommandBarItem
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/CommandBar/delete24Filled.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/CommandBar/delete24Filled.imageset/ic_fluent_delete_24_filled.pdf
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
Labels: New API

#1310 ability to customize resizehandle a11ylabel for BottomCommandingController
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
Labels: New API

#1303 [Fluent 2 iOS] BadgeView update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeViewDemoController.swift
  ios/FluentUI/Badge Field/BadgeView.swift
Labels: fluent2-colors 🎨

#1323 Fix SearchBar placeholder text contrast issue
  ios/FluentUI/Navigation/SearchBar.swift
Labels: fluent2-colors 🎨

#1320 Fix TableViewCell grouped style header color
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: fluent2-colors 🎨

#1322 Update Shimmer colors
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI/Shimmer/ShimmerTokenSet.swift
Labels: fluent2-colors 🎨

#1324 Update Tooltip colors
  ios/FluentUI/Tooltip/TooltipView.swift
Labels: fluent2-colors 🎨

#1325 Fix secondary label contrast issue
  ios/FluentUI/Label/Label.swift
Labels: fluent2-colors 🎨

#1329 [Fluent 2 iOS] TableViewCellFileAccessoryView colors update
  ios/FluentUI/Other Cells/TableViewCellFileAccessoryView.swift
Labels: fluent2-colors 🎨

#1331 Merge main into fluent2-colors
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BottomSheetDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 20_2x-1.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 20_2x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 20_3x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 29_2x-1.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 29_2x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 29_3x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 40_2x-1.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 40_2x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 40_3x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 60_2x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 60_3x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 76_2x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/ 83.5_2x.png
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/CommandBar/delete24Filled.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/CommandBar/delete24Filled.imageset/ic_fluent_delete_24_filled.pdf
  ios/FluentUI/AvatarGroup/AvatarGroup.swift
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/ Icon-128_2x-1.png
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/ Icon-128_2x.png
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/ Icon-16_2x.png
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/ Icon-256_2x.png
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/ Icon-32_2x.png
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/ Icon-512_2x.png
  macos/FluentUITestApp/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: fluent2-colors 🎨
