Repository microsoft/fluentui-apple, pull requests merged in 2022-09, with the labels that each got.

#1203 Align Notification Border with Figma
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/NotificationModifiers.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
Labels: API break

#1189 [Fluent 2 iOS] HUD colors & padding update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/HUDDemoController.swift
  ios/FluentUI/HUD/HUDTokens.swift
  ios/FluentUI/HUD/HeadsUpDisplay.swift
Labels: fluent2-colors 🎨

#1202 [Fluent 2 iOS] NotificationView colors update
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Notification/NotificationTokens.swift
Labels: fluent2-colors 🎨

#1216 Remove all usage of UIScreen.main
  ios/FluentUI.Demo/FluentUI.Demo/SceneDelegate.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewCellSampleData.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Badge Field/BadgeField.swift
  ios/FluentUI/Badge Field/BadgeView.swift
  ios/FluentUI/Calendar/CalendarView.swift
  ios/FluentUI/Calendar/CalendarViewLayout.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayCell.swift
  ios/FluentUI/Calendar/Views/CalendarViewWeekdayHeadingView.swift
  ios/FluentUI/Card/CardView.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerViewComponentCell.swift
  ios/FluentUI/Drawer/DrawerController.swift
  ios/FluentUI/Drawer/DrawerPresentationController.swift
  ios/FluentUI/Extensions/String+Extension.swift
  ios/FluentUI/Extensions/UIFont+Extension.swift
  ios/FluentUI/Extensions/UIScreen+Extension.swift
  ios/FluentUI/Extensions/UIView+Extensions.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Other Cells/ActivityIndicatorCell.swift
  ios/FluentUI/People Picker/PeoplePicker.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Presenters/PageCardPresenterController.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/Separator/Separator.swift
  ios/FluentUI/Shimmer/ShimmerView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/UITableViewCell+Extension.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
Labels: API break

#1220 Removing spacing and padding values from token sets
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellFileAccessoryViewDemoController.swift
  ios/FluentUI/ActivityIndicator/ActivityIndicator.swift
  ios/FluentUI/ActivityIndicator/ActivityIndicatorTokenSet.swift
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/AvatarGroup/AvatarGroup.swift
  ios/FluentUI/Card Nudge/CardNudge.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/HUD/HeadsUpDisplay.swift
  ios/FluentUI/HUD/HeadsUpDisplayTokenSet.swift
  ios/FluentUI/IndeterminateProgressBar/IndeterminateProgressBar.swift
  ios/FluentUI/IndeterminateProgressBar/IndeterminateProgressBarTokenSet.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Other Cells/ActivityIndicatorCell.swift
  ios/FluentUI/Other Cells/CenteredLabelCell.swift
  ios/FluentUI/PersonaButton/PersonaButton.swift
  ios/FluentUI/PersonaButton/PersonaButtonTokenSet.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: API break

#1228 [fluent2 tokens] merge main -> fluent2_tokens
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/SceneDelegate.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewCellSampleData.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Badge Field/BadgeField.swift
  ios/FluentUI/Badge Field/BadgeView.swift
  ios/FluentUI/Calendar/CalendarView.swift
  ios/FluentUI/Calendar/CalendarViewLayout.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayCell.swift
  ios/FluentUI/Calendar/Views/CalendarViewWeekdayHeadingView.swift
  ios/FluentUI/Card/CardView.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
  ios/FluentUI/Core/Theme/Tokens/LinearGradientInfo.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerViewComponentCell.swift
  ios/FluentUI/Drawer/DrawerController.swift
  ios/FluentUI/Drawer/DrawerPresentationController.swift
  ios/FluentUI/Extensions/String+Extension.swift
  ios/FluentUI/Extensions/UIFont+Extension.swift
  ios/FluentUI/Extensions/UIScreen+Extension.swift
  ios/FluentUI/Extensions/UIView+Extensions.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/NotificationModifiers.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Other Cells/ActivityIndicatorCell.swift
  ios/FluentUI/People Picker/PeoplePicker.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
  ios/FluentUI/Presenters/PageCardPresenterController.swift
  ios/FluentUI/SegmentedControl/SegmentPillButton.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/Separator/Separator.swift
  ios/FluentUI/Shimmer/MSFShimmerView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/UITableViewCell+Extension.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
  ios/FluentUI/Vnext/Divider/Divider.swift
  ios/FluentUI/Vnext/Divider/DividerTokenSet.swift
  ios/FluentUI/Vnext/Divider/MSFDivider.swift
Labels: fluent2-tokens

#1230 Bumping FluentUI version (0.8.0)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1204 introduced a Medium Fluent Button Size
  macos/FluentUI/Button/Button.swift
  macos/FluentUITestViewControllers/TestButtonViewController.swift
Labels: New API

#1238 [main_0.8] Bumping FluentUI version (0.8.1)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1223 [Fluent 2 iOS] Contextual Command Bar colors update
  ios/FluentUI/Command Bar/CommandBarButton.swift
Labels: fluent2-colors 🎨

#1194 Update Avatar size ramp
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarGroupDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/Avatar/MSFAvatar.swift
  ios/FluentUI/AvatarGroup/AvatarGroupTokenSet.swift
  ios/FluentUI/Navigation/Views/LargeTitleView.swift
  ios/FluentUI/People Picker/PersonaCell.swift
  ios/FluentUI/PersonaButton/PersonaButtonTokenSet.swift
  ios/FluentUI/Tab Bar/SideTabBar.swift
Labels: API break

#1207 Bottom sheet collapsed height resolver API
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BottomSheetDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Bottom Sheet/ContentHeightResolutionContext.swift
Labels: New API

#1242 Add swipe to hide API to bottom sheet
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BottomSheetDemoController.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
Labels: New API

#1248 Reverting regression in TableViewCell API
  ios/FluentUI/Table View/TableViewCell.swift
Labels: API break

#1253 [main_0.8] Bumping FluentUI version (0.8.2)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1227 Clean up Button usage of APIs being deprecated in iOS 15
  ios/FluentUI/Button/Button.swift
Labels: API break

#1246 [Fluent 2 iOS] DateTimePicker + CalendarView update
  ios/FluentUI.Tests/DatePickerControllerTests.swift
  ios/FluentUI/Calendar/CalendarView.swift
  ios/FluentUI/Calendar/CalendarViewDataSource.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayCell.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayMonthCell.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayMonthYearCell.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayTodayCell.swift
  ios/FluentUI/Calendar/Views/CalendarViewWeekdayHeadingView.swift
  ios/FluentUI/Core/FluentUIFramework.swift
  ios/FluentUI/Date Time Pickers/Date Picker/DatePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/DateTimePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerView.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerViewComponentCell.swift
  ios/FluentUI/Presenters/CardPresenterNavigationController.swift
Labels: fluent2-colors 🎨

#1256 [Fluent 2 iOS] SegmentedControl colors update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
Labels: fluent2-colors 🎨, New API

#1257 [Fluent2 tokens] Merge main to fluent2-tokens
  .ado/fluentui-apple-publish-nuget.yml
  .ado/templates/apple-xcode-build.yml
  .ado/templates/apple-xcode-select.yml
  .ado/templates/fluentui-apple-build-zip.yml
  .ado/templates/fluentui-apple-publish-nuget-job.yml
  .ado/xcconfig/publish_overrides.xcconfig
  .ado/xcconfig/publish_overrides_ios_device.xcconfig
  .ado/xcconfig/publish_staticanalysis.xcconfig
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarGroupDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BottomSheetDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/LeftNavDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ListDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/Avatar/MSFAvatar.swift
  ios/FluentUI/AvatarGroup/AvatarGroupTokenSet.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Bottom Sheet/ContentHeightResolutionContext.swift
  ios/FluentUI/Button/ButtonLegacy.swift
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Navigation/Views/LargeTitleView.swift
  ios/FluentUI/People Picker/PersonaCell.swift
  ios/FluentUI/PersonaButton/PersonaButtonTokenSet.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Vnext/Persona/PersonaView.swift
  macos/FluentUI/Button/Button.swift
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
  macos/FluentUITestViewControllers/TestButtonViewController.swift
Labels: fluent2-tokens

#1264 [main_0.8] Bumping FluentUI version (0.8.3)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1267 [main_0.8] Bumping FluentUI version (0.8.4)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1224 [Fluent 2 iOS] ResizingHandleView color update
  ios/FluentUI/ResizingHandleView/ResizingHandleView.swift
Labels: fluent2-colors 🎨

#1270 [Fluent 2 iOS] Add new alias tokens
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AliasColorTokensDemoController.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨
