Repository microsoft/fluentui-apple, pull requests merged in 2022-06, with the labels that each got.

#978 [vNext-tokens] Tokenizing TableViewCell
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellFileAccessoryViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewTokens.swift
Labels: vnext-tokens

#996 [vNext Tokens] SideTabBar Tokenization
  ios/FluentUI.Demo/FluentUI.Demo/DemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Tab Bar/SideTabBarTokens.swift
Labels: vnext-tokens

#1003 [main -> vnext_tokens] Update with latest main changes to unblock SegmentedControl work
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Badge Field/BadgeField.swift
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
  ios/FluentUI/Core/ControlHostingView.swift
  ios/FluentUI/Navigation/SearchBar.swift
  ios/FluentUI/SegmentedControl/SegmentItem.swift
  ios/FluentUI/SegmentedControl/SegmentPillButton.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: vnext-tokens

#1005 [Tokens] Simplify theme token lookup and generation
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ButtonDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CardNudgeDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DividerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/HUDDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PillButtonBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TabBarViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI/Core/Theme/FluentTheme.swift
  ios/FluentUI/Core/Theme/Tokens/TokenizedControl.swift
Labels: vnext-tokens

#1006 [vNext Tokens] Convert SegmentedControl from UIControl to UIView
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI/Date Time Pickers/Date Picker/DatePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/DateTimePickerController.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
Labels: fluent2-tokens, API break

#1010 Bumping versions for FluentUI release (0.5.1).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1004 Tokenize ShimmerView
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Shimmer/ShimmerLinesView.swift
  ios/FluentUI/Shimmer/ShimmerTokens.swift
  ios/FluentUI/Shimmer/ShimmerView.swift
Labels: fluent2-tokens, API break

#1020 [Fluent2 iOS] Updating Alias Tokens
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1030 [Fluent2 iOS] Replace Colorful tokens with Brand tokens
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1027 Updated activity indicator color tokens
  ios/FluentUI/ActivityIndicator/ActivityIndicatorTokens.swift
Labels: fluent2-colors 🎨

#1036 Persona Button Colors Update
  ios/FluentUI/PersonaButton/PersonaButtonTokens.swift
Labels: fluent2-colors 🎨

#1029 Enable Fluent Notification Customization
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/MSFNotificationView.swift
  ios/FluentUI/Notification/NotificationModifiers.swift
  ios/FluentUI/Notification/NotificationTokens.swift
Labels: fluent2-tokens

#1037 Persona Button Carousel Color Tokens Update
  ios/FluentUI/PersonaButtonCarousel/PersonaButtonCarouselTokens.swift
Labels: fluent2-colors 🎨

#1035 [main -> fluent2-tokens] Merging latest state of the main branch into fluent2-tokens after release of version 0.5.2.
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DateTimePickerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TabBarViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  ios/FluentUI.Tests/DatePickerControllerTests.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Calendar/CalendarConfiguration.swift
  ios/FluentUI/Date Time Pickers/Date Picker/DatePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/DateTimePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerView.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerViewDataSource.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerViewLayout.swift
  ios/FluentUI/Date Time Pickers/DateTimePicker.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/docs/Controls/.attachments/Date-Calendar.png
  ios/docs/Controls/.attachments/Date-Components.png
  ios/docs/Controls/.attachments/DateRange-Calendar-Paged.png
  ios/docs/Controls/.attachments/DateRange-Calendar-Tabbed.png
  ios/docs/Controls/.attachments/DateRange-Components.png
  ios/docs/Controls/.attachments/DateTime-Calendar-1.png
  ios/docs/Controls/.attachments/DateTime-Calendar-2.png
  ios/docs/Controls/.attachments/DateTime-Components.png
  ios/docs/Controls/.attachments/DateTimeRange.png
  ios/docs/Controls/DateTimePicker.md
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: fluent2-tokens

#1032 [Fluent2 iOS] Moved new color tokens into a consolidated enum
  ios/FluentUI/ActivityIndicator/ActivityIndicatorTokens.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/IndeterminateProgressBar/IndeterminateProgressBarTokens.swift
  ios/FluentUI/PersonaButton/PersonaButtonTokens.swift
  ios/FluentUI/PersonaButtonCarousel/PersonaButtonCarouselTokens.swift
Labels: fluent2-colors 🎨

#1044 [Fluent2 Tokens] Update stored TVC tokens to be computed
  ios/FluentUI/Table View/TableViewTokens.swift
Labels: fluent2-tokens

#1045 Avatar Color Tokens Update
  ios/FluentUI/Avatar/AvatarTokens.swift
Labels: fluent2-colors 🎨

#1042 [Fluent2 Tokens] Update MSFNotification APIs
  ios/FluentUI/Notification/MSFNotificationView.swift
Labels: fluent2-tokens
