Repository microsoft/fluentui-apple, pull requests merged in 2022-07, with the labels that each got.

#1052 [Fluent Tokens] Fix Theming Bug with SideTabBar
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI/Tab Bar/SideTabBar.swift
Labels: fluent2-tokens

#1051 Tooltip Colors Update
  ios/FluentUI/Tooltip/TooltipView.swift
Labels: fluent2-colors 🎨

#1050 SearchBar Colors Update
  ios/FluentUI/Navigation/SearchBar.swift
Labels: fluent2-colors 🎨

#1055 [Fluent2 Tokens] Add an optional trailing image to the Notification
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI/Notification/FluentNotification.swift
Labels: fluent2-tokens

#1056 Fixing text color update in TableViewCell for rich text support
  ios/FluentUI/Table View/TableViewCell.swift
Labels: fluent2-tokens

#1062 Adding rich text support for fonts in TableViewCell
  ios/FluentUI/Table View/TableViewCell.swift
Labels: fluent2-tokens

#1065 [Fluent 2 iOS] Card Colors Update
  ios/FluentUI/Card/CardView.swift
Labels: fluent2-colors 🎨

#1067 Fixing NSAttributedString not reflecting changes in Label
  ios/FluentUI/Label/Label.swift
Labels: fluent2-tokens

#1071 [Fluent 2 iOS] Fixing SearchBar's brand colors for dark mode
  ios/FluentUI/Navigation/SearchBar.swift
Labels: fluent2-colors 🎨

#1073 [Fluent2-Tokens] [cherry-pick] Fix device build by restoring correct profiles (#1041)
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
Labels: fluent2-tokens

#1076 [Fluent2 Tokens] Add MSFNotification convenience init with just MSFNotificationStyle
  ios/FluentUI/Notification/MSFNotificationView.swift
Labels: fluent2-tokens, API break

#1068 [Fluent 2 iOS] Navigation bar colors update
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Navigation/Shy Header/ShyHeaderController.swift
  ios/FluentUI/Navigation/UINavigationItem+Navigation.swift
Labels: fluent2-colors 🎨

#1081 Bumping versions for FluentUI release (0.5.3).
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1078 [Fluent2 Tokens] Fix Notification VoiceOver grouping
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI/Notification/FluentNotification.swift
Labels: fluent2-tokens

#1083 [Fluent2 Tokens] Remove unused Notification color assets
  apple/Resources/FluentUI-apple.xcassets/FluentColors/charcoalPrimary.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/charcoalShade50.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/charcoalTint50.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/charcoalTint60.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/redShade10.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/redShade40.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/redTint20.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/redTint60.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/yellowShade40.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/yellowShade50.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/yellowTint20.colorset/Contents.json
  apple/Resources/FluentUI-apple.xcassets/FluentColors/yellowTint50.colorset/Contents.json
Labels: fluent2-tokens

#1080 [Fluent 2 iOS] BadgeField colors update
  ios/FluentUI/Badge Field/BadgeField.swift
Labels: fluent2-colors 🎨

#1086 [Fluent2 Tokens] Update MSFNotificationState style to be settable
  ios/FluentUI/Notification/FluentNotification.swift
Labels: fluent2-tokens

#1082 Updating + improving TableViewCell fonts
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewTokens.swift
Labels: fluent2-tokens

#1097 UIBackgroundConfiguration to change the cell color
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarGroupDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CardNudgeDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DividerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PersonaButtonCarouselDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellFileAccessoryViewDemoController.swift
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Other Cells/ActivityIndicatorCell.swift
  ios/FluentUI/Other Cells/CenteredLabelCell.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewTokens.swift
Labels: fluent2-tokens, API break

#1095 [Fluent2 Tokens] Moving `Avatar` calculated colors out of `AvatarTokens`
  ios/FluentUI.Tests/ColorTests.swift
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/AvatarTokens.swift
Labels: fluent2-tokens

#1088 Expanding label width in TableViewCell to prevent attributedText from getting cut off
  ios/FluentUI/Table View/TableViewCell.swift
Labels: fluent2-tokens

#1098 [Fluent 2 iOS] Update Shadow definitions
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1099 fix build warnings in fluent2-tokens
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/LeftNav/ic_fluent_settings_24_regular.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/LeftNav/ic_fluent_settings_24_regular.imageset/ic_fluent_settings_24_regular.pdf
  ios/FluentUI/Shimmer/ShimmerLinesView.swift
Labels: fluent2-tokens

#1102 [Fluent 2 iOS] Merge main to fluent2-colors
  MicrosoftFluentUI.podspec
  README.md
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarGroupDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CardNudgeDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/IndeterminateProgressBarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PersonaButtonCarouselDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellFileAccessoryViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarButtonGroupView.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarItem.swift
  ios/FluentUI/Core/SwiftUI+ViewModifiers.swift
  ios/FluentUI/Core/SwiftUI+ViewPresentation.swift
  ios/FluentUI/Core/Theme/FluentTheme.swift
  ios/FluentUI/Core/Theme/Tokens/TokenizedControl.swift
  ios/FluentUI/Core/UIKit+SwiftUI_interoperability.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/DateTimePickerController.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerView.swift
  ios/FluentUI/Extensions/UIApplication+Extensions.swift
  ios/FluentUI/IndeterminateProgressBar/IndeterminateProgressBar.swift
  ios/FluentUI/Label/Label.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/MSFNotificationView.swift
  ios/FluentUI/Notification/NotificationModifiers.swift
  ios/FluentUI/Notification/NotificationTokens.swift
  ios/FluentUI/Notification/NotificationView.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/Other Cells/ActivityIndicatorCell.swift
  ios/FluentUI/Other Cells/BooleanCell.swift
  ios/FluentUI/Other Cells/CenteredLabelCell.swift
  ios/FluentUI/People Picker/PersonaCell.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewTokens.swift
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUI/Link/Link.swift
  macos/FluentUITestApp/FluentUITestApp-Info.plist
  macos/FluentUITestViewControllers/TestColorViewController.swift
  macos/FluentUITestViewControllers/TestLinkViewController.swift
  macos/xcode/FluentUI_common.xcconfig
Labels: fluent2-colors 🎨

#1103 Additional Notification API and behavior changes
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/MSFNotification.swift
Labels: API break

#1094 [Fluent 2 iOS] TableViewHeaderFooterView colors update
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: fluent2-colors 🎨

#1104 [Fluent2 TokenSet] Merging in more controls
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CardNudgeDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/ActivityIndicator/ActivityIndicator.swift
  ios/FluentUI/ActivityIndicator/ActivityIndicatorModifiers.swift
  ios/FluentUI/ActivityIndicator/ActivityIndicatorTokenSet.swift
  ios/FluentUI/ActivityIndicator/ActivityIndicatorTokens.swift
  ios/FluentUI/ActivityIndicator/MSFActivityIndicator.swift
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/AvatarModifiers.swift
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/Avatar/AvatarTokens.swift
  ios/FluentUI/Avatar/MSFAvatar.swift
  ios/FluentUI/AvatarGroup/AvatarGroup.swift
  ios/FluentUI/AvatarGroup/AvatarGroupModifiers.swift
  ios/FluentUI/AvatarGroup/AvatarGroupTokenSet.swift
  ios/FluentUI/AvatarGroup/AvatarGroupTokens.swift
  ios/FluentUI/AvatarGroup/MSFAvatarGroup.swift
  ios/FluentUI/Card Nudge/CardNudge.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Card Nudge/MSFCardNudge.swift
  ios/FluentUI/Core/Theme/FluentTheme.swift
  ios/FluentUI/Core/Theme/Tokens/ControlTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/TokenizedControlView.swift
  ios/FluentUI/Drawer/DrawerController.swift
Labels: fluent2-tokens
