Repository microsoft/fluentui-apple, pull requests merged in 2022-12, with the labels that each got.

#1405 Update GlobalTokens to include new ramps
  ios/FluentUI.Demo/FluentUI.Demo/Demos/HUDDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellFileAccessoryViewDemoController.swift
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/AvatarGroup/AvatarGroupTokenSet.swift
  ios/FluentUI/Button/Button.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Divider/DividerTokenSet.swift
  ios/FluentUI/HUD/HeadsUpDisplayTokenSet.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/PersonaButton/PersonaButtonTokenSet.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/SegmentedControl/SegmentedControlTokenSet.swift
  ios/FluentUI/Shimmer/ShimmerTokenSet.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: fluent2-colors 🎨

#1426 [Fluent2 iOS] Fluent2 BadgeLabel
  ios/FluentUI/Label/BadgeLabel.swift
Labels: fluent2-colors 🎨

#1436 [Fluent 2 iOS] TwoLineTitleView + LargeTitleView update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TooltipDemoController.swift
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Navigation/Views/LargeTitleView.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
Labels: fluent2-colors 🎨

#1438 [Fluent 2 iOS] Merge Main
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ButtonDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PersonaListViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SegmentedControlDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Button/Button.swift
  ios/FluentUI/Button/ButtonTokenSet.swift
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Command Bar/CommandBarButton.swift
  ios/FluentUI/Command Bar/CommandBarButtonGroupView.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Command Bar/CommandBarTokenSet.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
  ios/FluentUI/Resources/Localization/ar.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ca.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/cs.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/da.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/de.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/el.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/en-GB.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es-MX.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/he.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hu.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/id.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/it.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ja.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ko.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ms.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nb-NO.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-BR.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-PT.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ro.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ru.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sv.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/th.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/tr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/uk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/vi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hans.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hant.lproj/Localizable.strings
  ios/FluentUI/SegmentedControl/SegmentPillButton.swift
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
  ios/FluentUI/Table View/TableViewCell.swift
  macos/FluentUI/AvatarView/AvatarView.swift
  macos/FluentUITestViewControllers/TestAvatarViewController.swift
  macos/FluentUIUnitTest/AvatarViewTests.swift
Labels: fluent2-colors 🎨

#1447 [Fluent 2 iOS] PageCardPresenter update
  ios/FluentUI/Presenters/PageCardPresenterController.swift
Labels: fluent2-colors 🎨

#1453 [fluent2 colors] Update Button to match Fluent 2 designs
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BottomSheetDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ButtonDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DrawerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PopupMenuObjCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellFileAccessoryViewDemoController.swift
  ios/FluentUI/Button/Button.swift
  ios/FluentUI/Button/ButtonTokenSet.swift
Labels: API break, fluent2-colors 🎨

#1457 [fluent2-colors] Merge `main` before all the `Divider` stuff
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fluent2-colors 🎨

#1460 [Fluent2 iOS] Cherry-Pick Separator
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeFieldDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/IndeterminateProgressBarDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PeoplePickerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShimmerLinesViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Bottom Commanding/BottomCommandingController.swift
  ios/FluentUI/Calendar/CalendarView.swift
  ios/FluentUI/Date Time Pickers/Date Time Picker/Views/DateTimePickerView.swift
  ios/FluentUI/Drawer/DrawerPresentationController.swift
  ios/FluentUI/Navigation/Shy Header/ShyHeaderView.swift
  ios/FluentUI/Other Cells/ActionsCell.swift
  ios/FluentUI/People Picker/PeoplePicker.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
  ios/FluentUI/Separator/Separator.swift
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Tab Bar/TabBarView.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/README.md
Labels: fluent2-colors 🎨

#1463 [Fluent2 iOS] Merge Main
  ios/FluentUI.Demo/FluentUI.Demo/DemoAppearanceController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Core/Theme/FluentTheme.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Core/Theme/Tokens/DynamicColor.swift
  ios/FluentUI/Core/Theme/Tokens/FontInfo.swift
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
  ios/FluentUI/Core/Theme/Tokens/TokenizedControlView.swift
  ios/FluentUI/Extensions/UIColor+Extensions.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
Labels: fluent2-colors 🎨

#1446 Adding additional leading view to TableViewCell
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewCellSampleData.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewSampleData.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: API break

#1464 Rewrite `ShadowTokensDemoController`
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShadowTokensDemoController.swift
Labels: fluent2-colors 🎨

#1471 Add documentation for Button
  ios/docs/Controls/.attachments/Button-Borderless.png
  ios/docs/Controls/.attachments/Button-Danger-Filled.png
  ios/docs/Controls/.attachments/Button-Danger-Outline.png
  ios/docs/Controls/.attachments/Button-Primary-Filled.png
  ios/docs/Controls/.attachments/Button-Primary-Outline.png
  ios/docs/Controls/.attachments/Button-Secondary-Outline.png
  ios/docs/Controls/.attachments/Button-Tertiary-Outline.png
  ios/docs/Controls/Button.md
Labels: documentation

#1473 Fix png filenames in tooltip documentation
  ios/docs/Controls/Tooltip.md
Labels: documentation

#1470 [Fluent 2 iOS] ColoredPillBackgroundView update
  ios/FluentUI.Demo/FluentUI.Demo/ColoredPillBackgroundView.swift
Labels: fluent2-colors 🎨
