Repository microsoft/fluentui-apple, pull requests merged in 2022-08, with the labels that each got.

#1072 [Fluent 2 iOS] Updating BottomSheetController colors to Fluent 2 colors
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
Labels: fluent2-colors 🎨

#1137 [Fluent 2 iOS] Tooltip shadow update
  ios/FluentUI/Tooltip/TooltipView.swift
Labels: fluent2-colors 🎨

#1113 [Fluent 2 iOS] Label colors update
  ios/FluentUI.Demo/FluentUI.Demo/Demos/LabelDemoController.swift
  ios/FluentUI/Label/Label.swift
Labels: fluent2-colors 🎨

#1142 [Fluent 2 iOS] Adding Dark Elevated colors
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1159 Adjust Notification Padding Tokens
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/NotificationTokens.swift
Labels: API break

#1162 [Fluent2 Tokens] Convert Notification to use ShadowInfo token
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Core/Theme/Tokens/ControlTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
Labels: fluent2-tokens, API break

#1126 [Fluent 2 iOS] Created new alias tokens for shared colors
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨

#1147 [Fluent 2 iOS] TableViewCell colors update (1/2)
  ios/FluentUI/Table View/TableViewTokens.swift
Labels: fluent2-colors 🎨

#1163 [Fluent 2 iOS] Added ColorAliasTokensDemoController to demo app
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorAliasTokensDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorGlobalTokensDemoController.swift
Labels: fluent2-colors 🎨

#1100 Bumping version number to 0.7.0
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1168 [Fluent 2 iOS] Add ShadowTokensDemoController to demo app
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AliasColorTokensDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/GlobalColorTokensDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShadowTokensDemoController.swift
Labels: fluent2-colors 🎨

#1182 [Fluent 2 iOS] PillButtonBar Update
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
  ios/FluentUI/Pill Button Bar/PillButtonStyle.swift
Labels: fluent2-colors 🎨

#1152 Make `GlobalTokens` immutable
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CardNudgeDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorTokensDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/HUDDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TypographyTokensDemoController.swift
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/AvatarTokens.swift
  ios/FluentUI/AvatarGroup/AvatarGroupTokens.swift
  ios/FluentUI/Card Nudge/CardNudgeTokens.swift
  ios/FluentUI/Core/Colors.swift
  ios/FluentUI/Core/Theme/FluentTheme.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Core/Theme/Tokens/ControlTokens.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Core/Theme/Tokens/TokenSet.swift
  ios/FluentUI/HUD/HUDTokens.swift
  ios/FluentUI/IndeterminateProgressBar/IndeterminateProgressBarTokens.swift
  ios/FluentUI/Notification/NotificationTokens.swift
  ios/FluentUI/PersonaButton/PersonaButtonTokens.swift
  ios/FluentUI/Table View/TableViewTokens.swift
Labels: API break

#1148 [Fluent 2 iOS] TableViewCell colors update (2/2)
  ios/FluentUI.Demo/FluentUI.Demo/DemoTableViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AvatarGroupDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ColorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/OtherCellsDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewSampleData.swift
  ios/FluentUI/People Picker/PersonaListView.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: API break, fluent2-colors 🎨

#1188 Creating `GradientInfo` and exposing as optional override on `FluentNotification`
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Core/Theme/Tokens/GradientInfo.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Notification/NotificationModifiers.swift
Labels: API break

#1190 [Fluent 2 iOS] TableViewHeaderFooterView color fix
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/TableViewHeaderFooterSampleData.swift
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: fluent2-colors 🎨

#1185 [fluent2-tokens] Tokenize PopupMenu
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PopupMenuDemoController.swift
  ios/FluentUI/Drawer/DrawerController.swift
  ios/FluentUI/Drawer/DrawerTokenSet.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
Labels: fluent2-tokens

#1201 [Fluent 2 iOS] Update shared alias colors names and values
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
Labels: fluent2-colors 🎨
