Repository microsoft/fluentui-apple, pull requests merged in 2023-06, with the labels that each got.

#1769 Update version to 17.3
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1775 Update version to 17.4
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1787 Update version to 0.18.0
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1793 [main_0.18] Use base 10 integer literals for InteractivePart (#1791)
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
Labels: Cherry-pick 🍒

#1794 [main_0.18] Check for existing titleView before creating a custom titleView (#1792)
  ios/FluentUI/Navigation/NavigationBar.swift
Labels: Cherry-pick 🍒

#1797 [main_0.18] Remove deprecated API `shouldAutorotate` in DrawerController (#1796)
  ios/FluentUI/Drawer/DrawerController.swift
Labels: Cherry-pick 🍒

#1798 Update version to 0.18.1
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1802 [main_0.17] Add a trailing constraint for CommandBar's scroll view (#1801)
  ios/FluentUI/Command Bar/CommandBar.swift
Labels: Cherry-pick 🍒

#1803 [main_0.18] Add a trailing constraint for CommandBar's scroll view (#1801)
  ios/FluentUI/Command Bar/CommandBar.swift
Labels: Cherry-pick 🍒

#1804 Update version to 0.17.6
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1805 Update version to 0.18.2
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1800 Exposing the UIView for accessoryTypeView in TableViewCell
  ios/FluentUI/Table View/TableViewCell.swift
Labels: New API

#1806 Update version to 0.19.0
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1810 [main_0.19] Reapply #1499 (#1808)
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Tab Bar/TabBarItemTokenSet.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
  ios/FluentUI/Tab Bar/TabBarView.swift
Labels: Cherry-pick 🍒

#1811 [main_0.19] Add internal init for PillButton that takes token overrides #1809
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
Labels: Cherry-pick 🍒

#1812 [main_0.19] Bump to 0.19.1
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update
