Repository microsoft/fluentui-apple, pull requests merged in 2023-01, with the labels that each got.

#1478 [Cherry-Pick] Update Date Picker test to start from `now` to fix test failure (#1477)
  ios/FluentUI.Tests/DatePickerControllerTests.swift
Labels: fluent2-colors 🎨

#1468 Initial standalone implementation of colors2.swift functionality
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoColorProviding2.h
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoColorProviding2.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Core/Colors2.swift
  ios/FluentUI/Core/Theme/Tokens/TokenSet.swift
Labels: fluent2-colors 🎨, New API

#1488 [main_0.10] Bumping FluentUI version (0.10.2)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1489 Re-add `DrawerController`'s objc colors
  ios/FluentUI/Drawer/DrawerController.swift
Labels: fluent2-colors 🎨

#1505 Re-add error style label
  ios/FluentUI.Demo/FluentUI.Demo/Demos/LabelDemoController.swift
  ios/FluentUI/Label/Label.swift
Labels: fluent2-colors 🎨

#1501 [Fluent2-Colors] Switch ColorProviding2 to use FluentThemeable
  ios/FluentUI.Demo/FluentUI.Demo/DemoColorThemes.swift
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI/Core/Colors2.swift
  ios/FluentUI/Core/Theme/FluentTheme.swift
Labels: fluent2-colors 🎨

#1500 Update TableViewCell sublabel accessory view margin
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/ic_fluent_lock_closed_20_regular.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/ic_fluent_lock_closed_20_regular.imageset/ic_fluent_lock_closed_20_regular.pdf
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/ic_fluent_share_20_regular.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/ic_fluent_share_20_regular.imageset/ic_fluent_share_20_regular.pdf
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/shared-12x12.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/shared-12x12.imageset/ic_fluent_people_12_regular.pdf
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/success-12x12.imageset/Contents.json
  ios/FluentUI.Demo/FluentUI.Demo/Resources/Assets.xcassets/TableViewCell/success-12x12.imageset/success.pdf
  ios/FluentUI.Demo/FluentUI.Demo/TableViewCellSampleData.swift
  ios/FluentUI/Table View/TableViewCell.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: fluent2-colors 🎨

#1510 [Fluent 2 iOS] Alias token cleanup
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AliasColorTokensDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI/Avatar/MSFAvatarPresence.swift
  ios/FluentUI/Badge Field/BadgeView.swift
  ios/FluentUI/Button/ButtonTokenSet.swift
  ios/FluentUI/Core/Colors.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Label/BadgeLabel.swift
  ios/FluentUI/Label/Label.swift
  ios/FluentUI/Notification/NotificationTokenSet.swift
  ios/FluentUI/Pill Button Bar/PillButtonStyle.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: fluent2-colors 🎨

#1509 [Fluent 2 iOS] Removing colors.swift, renaming ColorProviding2 to ColorProviding
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUI.Demo/DemoColorThemes.swift
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/BadgeViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoColorProviding.h
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoColorProviding.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PopupMenuObjCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SearchBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/SwiftUI/FluentUIDemoToggle.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Core/ColorProviding.swift
  ios/FluentUI/Core/Colors.swift
  ios/FluentUI/Core/FluentUIFramework.swift
Labels: fluent2-colors 🎨

#1517 [main_0.11] Bumping FluentUI Apple Version (0.11.1)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1518 [Fluent 2 iOS] Fix SegmentedControl crash
  ios/FluentUI/SegmentedControl/SegmentedControl.swift
Labels: fluent2-colors 🎨

#1519 [Fluent 2 iOS] Remove unused tests
  ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
  ios/FluentUI.Demo/FluentUIDemoTests/ColorTokensTest.swift
  ios/FluentUI.Demo/FluentUIDemoTests/TypographyTokensTest.swift
Labels: fluent2-colors 🎨

#1520 Update Tooltip shadows
  ios/FluentUI/Tooltip/Tooltip.swift
  ios/FluentUI/Tooltip/TooltipView.swift
Labels: fluent2-colors 🎨

#1522 [Fluent 2 iOS] Removing more deprecated alias tokens
  ios/FluentUI.Demo/FluentUI.Demo/Demos/AliasColorTokensDemoController.swift
  ios/FluentUI/Calendar/Views/CalendarViewDayCell.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: fluent2-colors 🎨

#1521 Rename Shadowable & ShadowInfo's properties
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NotificationViewDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ShadowTokensDemoController.swift
  ios/FluentUI/Bottom Sheet/BottomSheetController.swift
  ios/FluentUI/Card/CardView.swift
  ios/FluentUI/Core/SwiftUI+ViewModifiers.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Core/Theme/Tokens/ControlTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
  ios/FluentUI/Notification/FluentNotification.swift
  ios/FluentUI/Tooltip/TooltipView.swift
Labels: fluent2-colors 🎨

#1535 Change TableViewCellDemoController's table view style to insetGroup
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewCellDemoController.swift
Labels: fluent2-colors 🎨

#1536 Bumping FluentUI version (0.12.0)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update
