Repository microsoft/fluentui-apple, pull requests merged in 2023-02, with the labels that each got.

#1527 Add support for two-line navigation bar titles
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Navigation/UINavigationItem+Navigation.swift
  ios/FluentUI/Navigation/Views/LargeTitleView.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
Labels: API break, New API

#1545 Rename icon size tokens
  ios/FluentUI/Avatar/AvatarTokenSet.swift
  ios/FluentUI/Card Nudge/CardNudgeTokenSet.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Table View/TableViewCellTokenSet.swift
Labels: API break

#1547 [fluent2-tokens] Remove dynamic color collections from control token sets
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PillButtonBarDemoController.swift
  ios/FluentUI/Core/Theme/Tokens/ButtonDynamicColors.swift
  ios/FluentUI/Core/Theme/Tokens/ControlTokenSet.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonTokenSet.swift
  ios/FluentUI/Vnext/Button/Button.swift
  ios/FluentUI/Vnext/Button/ButtonTokenSet.swift
Labels: fluent2-tokens

#1549 Remove ButtonDynamicColors.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Core/Theme/Tokens/ButtonDynamicColors.swift
Labels: API break

#1552 Expose custom Color initializers
  ios/FluentUI/Core/Theme/Tokens/DynamicColor.swift
Labels: New API

#1557 Adding new foreground token for Avatar activity
  ios/FluentUI/Avatar/Avatar.swift
  ios/FluentUI/Avatar/AvatarTokenSet.swift
Labels: New API

#1558 [main_0.12] Bumping FluentUI Apple Version (0.12.1)
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1567 rename buttonSize to ButtonSizeCategory
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ButtonDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/CommandBarDemoController.swift
  ios/FluentUI/Button/Button.swift
  ios/FluentUI/Button/ButtonTokenSet.swift
Labels: API break
