Repository microsoft/fluentui-apple, pull requests merged in 2023-10, with the labels that each got.

#1908 Adding titleNumberOfLines to PopupMenuItem
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Popup Menu/PopupMenuItem.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
Labels: New API

#1914 Deprecating `AliasTokens`
  ios/FluentUI.Demo/FluentUI.Demo/DemoColorThemes.swift
  ios/FluentUI.Demo/FluentUI.Demo/DemoListViewController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ActivityIndicatorDemoController_SwiftUI.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DrawerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/GlobalColorTokensDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TableViewHeaderFooterViewDemoController.swift
  ios/FluentUI/Badge Field/BadgeView.swift
  ios/FluentUI/Badge Field/BadgeViewTokenSet.swift
  ios/FluentUI/Calendar/Views/CalendarViewMonthBannerView.swift
  ios/FluentUI/Card/CardView.swift
  ios/FluentUI/Core/Theme/FluentTheme+Tokens.swift
  ios/FluentUI/Core/Theme/FluentTheme.swift
  ios/FluentUI/Core/Theme/Tokens/AliasTokens.swift
  ios/FluentUI/Core/Theme/Tokens/GlobalTokens.swift
  ios/FluentUI/Label/Label.swift
  ios/FluentUI/Navigation/BadgeLabelButton.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Presenters/PageCardPresenterController.swift
Labels: API break

#1920 [main_0.11] Update version to 0.11.2
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update
