Repository microsoft/fluentui-apple, pull requests merged in 2023-07, with the labels that each got.

#1823 Add support for custom trailing image of TwoLineTitleView's subtitle
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TwoLineTitleViewDemoController.swift
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Navigation/TwoLineTitleView+Navigation.swift
  ios/FluentUI/Navigation/UINavigationItem+Navigation.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
Labels: New API

#1825 Support leading image for both title and subtitle in TwoLineTitleView
  ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ObjectiveCDemoController.m
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TwoLineTitleViewDemoController.swift
  ios/FluentUI/Navigation/TwoLineTitleView+Navigation.swift
  ios/FluentUI/Navigation/UINavigationItem+Navigation.swift
  ios/FluentUI/Navigation/Views/AvatarTitleView.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleViewTokenSet.swift
Labels: New API

#1828 Update version to 0.20.0
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1834 [main_0.20] Cherry-pick #1831, #1826, and #1833
  ios/FluentUI/Command Bar/CommandBar.swift
  ios/FluentUI/Command Bar/CommandBarButtonGroupView.swift
  ios/FluentUI/Command Bar/CommandBarCommandGroupsView.swift
  ios/FluentUI/Core/ControlHostingView.swift
  ios/FluentUI/MultilineCommandBar/MultilineCommandBar.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
Labels: New API, Cherry-pick 🍒

#1849 Bump Version to 0.20.3
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update
