Repository microsoft/fluentui-apple, pull requests merged in 2023-04, with the labels that each got.

#1677 Bring tokenized PopupMenu, Drawer, TabBar, SideTabBar, PillButton/Bar & ResizingHandleView to main
  ios/FluentUI.Demo/FluentUI.Demo/DemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/DrawerDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PillButtonBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PopupMenuDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/SideTabBarDemoController.swift
  ios/FluentUI.Demo/FluentUI.Demo/Demos/TabBarViewDemoController.swift
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Core/Theme/Tokens/ShadowInfo.swift
  ios/FluentUI/Drawer/DrawerController.swift
  ios/FluentUI/Drawer/DrawerPresentationController.swift
  ios/FluentUI/Drawer/DrawerShadowView.swift
  ios/FluentUI/Drawer/DrawerTokenSet.swift
  ios/FluentUI/Drawer/DrawerTransitionAnimator.swift
  ios/FluentUI/Pill Button Bar/PillButton.swift
  ios/FluentUI/Pill Button Bar/PillButtonBar.swift
  ios/FluentUI/Pill Button Bar/PillButtonStyle.swift
  ios/FluentUI/Pill Button Bar/PillButtonTokenSet.swift
  ios/FluentUI/Popup Menu/PopupMenuController.swift
  ios/FluentUI/Popup Menu/PopupMenuItem.swift
  ios/FluentUI/Popup Menu/PopupMenuItemCell.swift
  ios/FluentUI/Popup Menu/PopupMenuItemTokenSet.swift
  ios/FluentUI/Popup Menu/PopupMenuTokenSet.swift
  ios/FluentUI/ResizingHandleView/ResizingHandleTokenSet.swift
  ios/FluentUI/ResizingHandleView/ResizingHandleView.swift
  ios/FluentUI/Tab Bar/SideTabBar.swift
  ios/FluentUI/Tab Bar/SideTabBarTokenSet.swift
  ios/FluentUI/Tab Bar/TabBarItemTokenSet.swift
  ios/FluentUI/Tab Bar/TabBarItemView.swift
  ios/FluentUI/Tab Bar/TabBarTokenSet.swift
  ios/FluentUI/Tab Bar/TabBarView.swift
Labels: API break, New API

#1689 Update version to 0.16
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1700 Add SearchBar documentation
  ios/docs/Controls/.attachments/SearchBar-On-Brand.png
  ios/docs/Controls/.attachments/SearchBar-On-Canvas.png
  ios/docs/Controls/.attachments/SearchBar-On-System.png
  ios/docs/Controls/SearchBar.md
Labels: documentation

#1704 Tokenizing Separator
  ios/FluentUI.xcodeproj/project.pbxproj
  ios/FluentUI/Separator/Separator.swift
  ios/FluentUI/Separator/SeparatorTokenSet.swift
Labels: New API
