Repository microsoft/fluentui-apple, pull requests merged in 2023-09, with the labels that each got.

#1884 [Localization] Localized Resource Files
  ios/FluentUI/Resources/Localization/ar.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ca.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/cs.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/da.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/de.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/el.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/en-GB.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es-MX.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/he.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hu.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/id.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/it.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ja.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ko.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ms.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nb-NO.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-BR.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-PT.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ro.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ru.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sv.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/th.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/tr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/uk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/vi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hans.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hant.lproj/Localizable.strings
Labels: Automated PR

#1886 [Localization] Localized Resource Files
  ios/FluentUI/Resources/Localization/cs.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/da.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/el.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es-MX.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/id.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/it.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ko.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ms.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nb-NO.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-BR.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ro.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ru.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sv.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/th.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/tr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/uk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/vi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hans.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hant.lproj/Localizable.strings
Labels: Automated PR

#1888 [Localization] Localized Resource Files
  ios/FluentUI/Resources/Localization/ca.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hr.lproj/Localizable.strings
Labels: Automated PR

#1890 [Localization] Localized Resource Files
  ios/FluentUI/Resources/Localization/ar.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/de.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/he.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hu.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ja.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-PT.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sk.lproj/Localizable.strings
Labels: Automated PR

#1894 [main_0.22] Cherry-pick: Fixing view cutoff in iPad when showing DrawerController (#1893)
  ios/FluentUI.Demo/FluentUI.Demo/Demos/PopupMenuDemoController.swift
  ios/FluentUI/Drawer/DrawerController.swift
Labels: Cherry-pick 🍒

#1896 [main_0.22] Bumping FluentUI Apple version to 0.22.1
  MicrosoftFluentUI.podspec
  ios/FluentUI.Demo/FluentUI.Demo/Info.plist
  ios/FluentUI.Resources/Info.plist
  macos/FluentUI/FluentUI-Info.plist
  macos/FluentUITestApp/FluentUITestApp-Info.plist
Labels: Version Update

#1900 [main_0.22] Fix TableViewHeaderFooterView being cropped on large text (#1899)
  ios/FluentUI/Table View/TableViewHeaderFooterView.swift
Labels: Cherry-pick 🍒

#1902 [main_0.22] Add accessibility label to navigation bar's back button (#1869)
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/Resources/Localization/ar.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ca.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/cs.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/da.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/de.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/el.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/en-GB.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/en.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es-MX.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/es.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/fr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/he.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/hu.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/id.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/it.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ja.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ko.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ms.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nb-NO.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/nl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pl.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-BR.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/pt-PT.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ro.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/ru.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/sv.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/th.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/tr.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/uk.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/vi.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hans.lproj/Localizable.strings
  ios/FluentUI/Resources/Localization/zh-Hant.lproj/Localizable.strings
Labels: Cherry-pick 🍒

#1904 [main_0.22] Fix NavigationBar's title view constraints (#1891)
  ios/FluentUI/Navigation/NavigationBar.swift
  ios/FluentUI/TwoLineTitleView/TwoLineTitleView.swift
Labels: Cherry-pick 🍒

#1906 Change alpha of ListItem when disabled (#1887)
  ios/FluentUI.Demo/FluentUI.Demo/Demos/ListItemDemoController_SwiftUI.swift
  ios/FluentUI/List/ListItem.swift
Labels: Cherry-pick 🍒
